import { useState } from 'react'

export default function EmailReport({ result }) {
    var [email, setEmail] = useState('')
    var [sending, setSending] = useState(false)
    var [sent, setSent] = useState(false)
    var [error, setError] = useState(null)
    var [open, setOpen] = useState(false)

    if (!result) return null

    function buildEmailBody() {
        var r = result.intelligenceReport || {}
        var score = result.momentumAccelerationScore || 0
        var kw = result.keyword || ''

        return [
            'NADI INTELLIGENCE REPORT',
            'Neural Ayurvedic & Digital Intelligence',
            '═══════════════════════════════════════',
            '',
            'TREND: ' + kw.toUpperCase(),
            'MAS Score: ' + score + '/100',
            'Classification: ' + (result.classification?.label || ''),
            'Market TAM: ₹' + (result.marketSizePotential?.tam || 0) + 'Cr',
            'Verdict: ' + (r.verdict || ''),
            'Confidence: ' + (r.confidence_level || ''),
            '',
            '───────────────────────────────────────',
            'EXECUTIVE SUMMARY',
            '───────────────────────────────────────',
            r.executive_summary || '',
            '',
            '───────────────────────────────────────',
            'WHY NOW — INDIA TIMING',
            '───────────────────────────────────────',
            r.why_now || '',
            '',
            '───────────────────────────────────────',
            'SIGNAL EVIDENCE',
            '───────────────────────────────────────',
            r.signal_evidence || '',
            '',
            '───────────────────────────────────────',
            'MARKET GAP',
            '───────────────────────────────────────',
            r.market_gap || '',
            '',
            '───────────────────────────────────────',
            'TARGET CONSUMER',
            '───────────────────────────────────────',
            r.target_consumer || '',
            '',
            '───────────────────────────────────────',
            'PRODUCT OPPORTUNITY',
            '───────────────────────────────────────',
            r.product_opportunity || '',
            '',
            '───────────────────────────────────────',
            'GO-TO-MARKET (90 DAYS)',
            '───────────────────────────────────────',
            r.go_to_market || '',
            '',
            '───────────────────────────────────────',
            'REVENUE MODEL',
            '───────────────────────────────────────',
            r.revenue_model || '',
            '',
            '───────────────────────────────────────',
            'COMPETITIVE MOAT',
            '───────────────────────────────────────',
            r.competitive_moat || '',
            '',
            '───────────────────────────────────────',
            'RISK ASSESSMENT',
            '───────────────────────────────────────',
            r.risk_assessment || '',
            '',
            '───────────────────────────────────────',
            'ACTION TIMELINE',
            '───────────────────────────────────────',
            r.action_timeline || '',
            '',
            '═══════════════════════════════════════',
            'LIVE SIGNAL DATA',
            '═══════════════════════════════════════',
            'Reddit mentions:    ' + (result.signals?.reddit || 0),
            'YouTube mentions:   ' + (result.signals?.youtube || 0),
            'News mentions:      ' + (result.signals?.news || 0),
            'Research papers:    ' + (result.signals?.research || 0),
            'Amazon IN products: ' + (result.signals?.ecommerce || 0),
            'Search momentum:    ' + (result.signals?.searchMomentum || 0) + '%',
            '',
            '═══════════════════════════════════════',
            'Generated by NADI v2.0',
            'nadi-wellness-radar-production.up.railway.app',
            'India Wellness Intelligence Platform',
            'Powered by DNA Trend Fingerprinting™',
            '═══════════════════════════════════════',
        ].join('\n')
    }

    function handleSend() {
        if (!email.trim() || !email.includes('@')) return
        setSending(true)
        setError(null)

        var subject = 'NADI Intelligence Report — ' + result.keyword + ' (MAS ' + result.momentumAccelerationScore + '/100)'
        var body = encodeURIComponent(buildEmailBody())
        var mailtoLink = 'mailto:' + email + '?subject=' + encodeURIComponent(subject) + '&body=' + body

        // Open mailto — works in most email clients
        window.location.href = mailtoLink

        setTimeout(function () {
            setSending(false)
            setSent(true)
        }, 1000)
    }

    return (
        <div style={{ marginTop: 12 }}>
            <button
                onClick={function () { setOpen(function (o) { return !o }) }}
                style={{
                    display: 'flex', alignItems: 'center', gap: 8,
                    padding: '7px 14px',
                    background: open ? 'rgba(201,168,76,0.1)' : 'rgba(201,168,76,0.05)',
                    border: '1px solid rgba(201,168,76,0.25)',
                    borderRadius: 6, cursor: 'pointer',
                    fontSize: 12, fontWeight: 600, color: 'var(--gold)',
                }}
            >
                📧 Email Report
            </button>

            {open && (
                <div style={{
                    marginTop: 8, padding: 16,
                    background: 'var(--bg-float)',
                    border: '1px solid rgba(201,168,76,0.2)',
                    borderRadius: 8,
                }}>
                    <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-1)', marginBottom: 4 }}>
                        Send Full Intelligence Report to Email
                    </div>
                    <div style={{ fontSize: 11, color: 'var(--text-3)', marginBottom: 14 }}>
                        The complete report for "{result.keyword}" will be sent as a formatted email to your inbox.
                    </div>

                    {sent ? (
                        <div style={{ fontSize: 13, color: 'var(--teal)', fontWeight: 600 }}>
                            ✅ Your email client has been opened with the report. Send it from there!
                        </div>
                    ) : (
                        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                            <input
                                type="email"
                                value={email}
                                onChange={function (e) { setEmail(e.target.value) }}
                                onKeyDown={function (e) { if (e.key === 'Enter') handleSend() }}
                                placeholder="your@email.com"
                                style={{ flex: 1, minWidth: 200, fontSize: 12 }}
                            />
                            <button
                                className="btn btn-primary"
                                onClick={handleSend}
                                disabled={sending || !email.trim() || !email.includes('@')}
                                style={{ height: 40 }}
                            >
                                {sending ? '⟳ Opening...' : 'Send Report →'}
                            </button>
                        </div>
                    )}

                    {error && (
                        <div style={{ fontSize: 11, color: 'var(--red)', marginTop: 8 }}>{error}</div>
                    )}
                </div>
            )}
        </div>
    )
}