// ShareBar — WhatsApp, copy, email share buttons for any result
export default function ShareBar({ result }) {
    if (!result) return null
    var r = result.intelligenceReport || {}
    var score = result.momentumAccelerationScore || 0
    var kw = result.keyword || ''

    function shareWhatsApp() {
        var text = `🧬 *NADI Intelligence Report*\n\n*${kw.toUpperCase()}*\nMAS Score: *${score}/100* ${result.classification?.emoji || ''}\n${result.classification?.label || ''}\n\n📊 Market TAM: ₹${result.marketSizePotential?.tam || '?'}Cr\n⏱ Time to mainstream: ${result.timeToMainstream || '?'}\n\n📝 *Verdict:*\n${(r.verdict || '').slice(0, 300)}\n\n_Analysed by NADI Wellness Radar — nadi-wellness-radar.onrender.com_`
        window.open('https://wa.me/?text=' + encodeURIComponent(text), '_blank')
    }

    function copyLink() {
        var text = `NADI Report: ${kw} — MAS ${score}/100\n\n${r.executive_summary || ''}\n\nVia NADI Wellness Radar`
        navigator.clipboard.writeText(text).then(() => {
            var btn = document.getElementById('copy-link-btn')
            if (btn) { btn.textContent = '✅ Copied'; setTimeout(() => { btn.textContent = '📋 Copy' }, 2000) }
        })
    }

    function downloadTxt() {
        var content = [
            'NADI INTELLIGENCE REPORT', '━'.repeat(40), '',
            'TREND: ' + kw.toUpperCase(), 'MAS SCORE: ' + score + '/100',
            'CLASSIFICATION: ' + result.classification?.label,
            'TAM: ₹' + result.marketSizePotential?.tam + 'Cr',
            'TIME TO MAINSTREAM: ' + result.timeToMainstream, '',
            '━'.repeat(40), 'EXECUTIVE SUMMARY', '━'.repeat(40),
            r.executive_summary, '',
            '━'.repeat(40), 'VERDICT', '━'.repeat(40),
            r.verdict, '',
            '━'.repeat(40), 'MARKET GAP', '━'.repeat(40),
            r.market_gap, '',
            '━'.repeat(40), 'PRODUCT OPPORTUNITY', '━'.repeat(40),
            r.product_opportunity, '',
            '━'.repeat(40), 'LIVE SIGNALS', '━'.repeat(40),
            'Reddit: ' + result.signals?.reddit,
            'YouTube: ' + result.signals?.youtube,
            'News: ' + result.signals?.news,
            'Research: ' + result.signals?.research,
            'Amazon Products: ' + result.signals?.ecommerce, '',
            'Generated by NADI Wellness Radar v3.0',
        ].join('\n')
        var blob = new Blob([content], { type: 'text/plain' })
        var a = document.createElement('a')
        a.href = URL.createObjectURL(blob)
        a.download = 'NADI-' + kw.replace(/[^a-z0-9]/gi, '_').slice(0, 30) + '.txt'
        a.click()
    }

    function saveToLibrary() {
        try {
            var saved = JSON.parse(localStorage.getItem('nadi_saved_reports') || '[]')
            var alreadySaved = saved.find(s => s.keyword === kw && s.type === 'Intelligence Report')
            if (alreadySaved) { alert('Already saved!'); return }
            saved.unshift({ id: Date.now().toString(), keyword: kw, type: 'Intelligence Report', summary: r.executive_summary?.slice(0, 300), score, savedAt: new Date().toISOString() })
            if (saved.length > 20) saved = saved.slice(0, 20)
            localStorage.setItem('nadi_saved_reports', JSON.stringify(saved))
            var btn = document.getElementById('save-report-btn')
            if (btn) { btn.textContent = '✅ Saved!'; setTimeout(() => { btn.textContent = '💾 Save' }, 2000) }
        } catch (e) { }
    }

    var btnStyle = { padding: '6px 12px', fontSize: 11, fontWeight: 600, borderRadius: 6, cursor: 'pointer', border: '1px solid', display: 'flex', alignItems: 'center', gap: 5 }

    return (
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 12, padding: '12px 0', borderTop: '1px solid var(--border-dim)' }}>
            <button onClick={shareWhatsApp} style={{ ...btnStyle, background: 'rgba(37,211,102,0.1)', borderColor: 'rgba(37,211,102,0.3)', color: '#25D366' }}>💬 WhatsApp</button>
            <button id="copy-link-btn" onClick={copyLink} style={{ ...btnStyle, background: 'transparent', borderColor: 'var(--border-dim)', color: 'var(--text-2)' }}>📋 Copy</button>
            <button onClick={downloadTxt} style={{ ...btnStyle, background: 'transparent', borderColor: 'var(--border-dim)', color: 'var(--text-2)' }}>📥 Download</button>
            <button id="save-report-btn" onClick={saveToLibrary} style={{ ...btnStyle, background: 'transparent', borderColor: 'var(--border-dim)', color: 'var(--text-2)' }}>💾 Save</button>
        </div>
    )
}