import { useState, useEffect } from 'react'
import axios from 'axios'
import ScoreRing from './ScoreRing.jsx'

var API_URL = import.meta.env.VITE_API_URL || ''

var WEEKLY_TRENDS = [
    'ashwagandha gummies India',
    'sea moss India',
    'berberine weight loss India',
    "lion's mane mushroom India",
    'shilajit supplement India',
    'moringa powder India',
    'collagen peptides India',
    'NMN anti-aging India',
]

function getWeekLabel() {
    var now = new Date()
    var start = new Date(now)
    start.setDate(now.getDate() - now.getDay() + 1)
    var end = new Date(start)
    end.setDate(start.getDate() + 6)
    var opts = { day: 'numeric', month: 'short' }
    return start.toLocaleDateString('en-IN', opts) + ' – ' + end.toLocaleDateString('en-IN', opts) + ', ' + now.getFullYear()
}

function scoreColor(s) {
    if (s >= 75) return 'var(--teal)'
    if (s >= 60) return 'var(--gold)'
    if (s >= 45) return 'var(--amber)'
    return 'var(--red)'
}

function classBadge(label) {
    var l = (label || '').toUpperCase()
    if (l.includes('BREAKOUT')) return 'badge-breakout'
    if (l.includes('EMERGING')) return 'badge-emerging'
    if (l.includes('NASCENT')) return 'badge-nascent'
    return 'badge-noise'
}

export default function WeeklyReport({ onAnalyze }) {
    var [results, setResults] = useState([])
    var [loading, setLoading] = useState(false)
    var [progress, setProgress] = useState(0)
    var [generated, setGenerated] = useState(false)
    var [email, setEmail] = useState('')
    var [subscribed, setSubscribed] = useState(false)
    var [emailSent, setEmailSent] = useState(false)
    var [emailError, setEmailError] = useState(null)
    var [sending, setSending] = useState(false)
    var [customKws, setCustomKws] = useState('')
    var [useCustom, setUseCustom] = useState(false)

    useEffect(function () {
        try {
            var sub = localStorage.getItem('nadi_email_sub')
            if (sub) { setEmail(sub); setSubscribed(true) }
            var cached = localStorage.getItem('nadi_weekly_report')
            if (cached) {
                var parsed = JSON.parse(cached)
                if (Date.now() - parsed.ts < 6 * 60 * 60 * 1000) { setResults(parsed.results); setGenerated(true) }
            }
        } catch (e) { }
    }, [])

    async function generateReport() {
        setLoading(true); setResults([]); setProgress(0)
        var trends = useCustom
            ? customKws.split('\n').map(k => k.trim()).filter(k => k.length > 1).slice(0, 10)
            : WEEKLY_TRENDS
        var collected = []
        for (var i = 0; i < trends.length; i++) {
            try {
                var res = await axios.post(API_URL + '/api/analyze', { keyword: trends[i] }, { timeout: 90000 })
                collected.push(res.data)
                var sorted = collected.slice().sort((a, b) => (b.momentumAccelerationScore || 0) - (a.momentumAccelerationScore || 0))
                setResults(sorted)
                setProgress(Math.round(((i + 1) / trends.length) * 100))
            } catch (e) { }
            await new Promise(r => setTimeout(r, 300))
        }
        var final = collected.slice().sort((a, b) => (b.momentumAccelerationScore || 0) - (a.momentumAccelerationScore || 0))
        setResults(final)
        setGenerated(true)
        setLoading(false)
        try { localStorage.setItem('nadi_weekly_report', JSON.stringify({ results: final, ts: Date.now() })) } catch (e) { }
    }

    function handleSubscribe() {
        if (!email.trim() || !email.includes('@')) return
        try { localStorage.setItem('nadi_email_sub', email) } catch (e) { }
        setSubscribed(true)
    }

    async function sendDigestEmail() {
        if (!email || !email.includes('@') || !results.length) return
        setSending(true); setEmailError(null)
        var top5 = results.slice(0, 5)
        var body = [
            'NADI WEEKLY WELLNESS DIGEST — ' + getWeekLabel(),
            '═'.repeat(50),
            '',
            'Top 5 Emerging Trends in Indian Wellness This Week:',
            '',
            ...top5.map((r, i) => [
                (i + 1) + '. ' + r.keyword.toUpperCase(),
                '   MAS Score: ' + r.momentumAccelerationScore + '/100 — ' + (r.classification?.label || ''),
                '   Market TAM: ₹' + (r.marketSizePotential?.tam || '?') + 'Cr',
                '   Trend: ' + (r.signals?.trendDirection || 'stable'),
                '   Verdict: ' + (r.intelligenceReport?.verdict || '').slice(0, 120),
                '',
            ].join('\n')),
            '─'.repeat(50),
            'Generated by NADI Wellness Radar — nadi-wellness-radar.onrender.com',
        ].join('\n')
        try {
            var res = await axios.post(API_URL + '/api/send-email', {
                to: email, subject: '🧬 NADI Weekly Digest — ' + getWeekLabel(), body,
            }, { timeout: 15000 })
            if (res.data.method === 'mailto') { window.location.href = res.data.mailtoUrl }
            setEmailSent(true)
        } catch (e) {
            setEmailError('Could not send email. Try again.')
        } finally { setSending(false) }
    }

    function shareWhatsApp() {
        if (!results.length) return
        var top5 = results.slice(0, 5)
        var text = '🧬 *NADI Weekly Digest — ' + getWeekLabel() + '*\n\n' +
            top5.map((r, i) => `${i + 1}. *${r.keyword}*\n   MAS ${r.momentumAccelerationScore}/100 ${r.classification?.emoji || ''} | ₹${r.marketSizePotential?.tam || '?'}Cr TAM`).join('\n\n') +
            '\n\n_India D2C Wellness Intelligence by NADI_'
        window.open('https://wa.me/?text=' + encodeURIComponent(text), '_blank')
    }

    function downloadCSV() {
        if (!results.length) return
        var csv = 'Rank,Keyword,MAS Score,Classification,TAM (Cr),Trend Direction,Verdict\n' +
            results.map((r, i) => [
                i + 1, '"' + r.keyword + '"', r.momentumAccelerationScore,
                '"' + (r.classification?.label || '') + '"',
                r.marketSizePotential?.tam || '',
                r.signals?.trendDirection || 'stable',
                '"' + (r.intelligenceReport?.verdict || '').slice(0, 80).replace(/"/g, "'") + '"',
            ].join(',')).join('\n')
        var a = document.createElement('a')
        a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
        a.download = 'NADI-weekly-' + new Date().toISOString().slice(0, 10) + '.csv'
        a.click()
    }

    return (
        <div style={{ maxWidth: 860 }}>
            {/* Header */}
            <div style={{ marginBottom: 24 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10 }}>
                    <div>
                        <h3 style={{ fontFamily: 'var(--f-display)', fontSize: 20, color: 'var(--gold)', marginBottom: 4 }}>📅 Weekly Trend Digest</h3>
                        <div style={{ fontFamily: 'var(--f-mono)', fontSize: 11, color: 'var(--text-3)' }}>Week of {getWeekLabel()}</div>
                    </div>
                    {generated && results.length > 0 && (
                        <div style={{ display: 'flex', gap: 8 }}>
                            <button onClick={downloadCSV} style={{ padding: '6px 12px', fontSize: 11, background: 'transparent', border: '1px solid var(--border-dim)', borderRadius: 6, color: 'var(--text-2)', cursor: 'pointer' }}>📥 CSV</button>
                            <button onClick={shareWhatsApp} style={{ padding: '6px 12px', fontSize: 11, background: 'rgba(37,211,102,0.1)', border: '1px solid rgba(37,211,102,0.3)', borderRadius: 6, color: '#25D366', cursor: 'pointer' }}>💬 WhatsApp</button>
                        </div>
                    )}
                </div>
            </div>

            {/* Custom keywords toggle */}
            <div className="card" style={{ padding: 16, marginBottom: 16 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: useCustom ? 12 : 0 }}>
                    <label style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', fontSize: 12, color: 'var(--text-2)' }}>
                        <input type="checkbox" checked={useCustom} onChange={e => setUseCustom(e.target.checked)} style={{ accentColor: 'var(--gold)' }} />
                        Use my own keywords (instead of default 8)
                    </label>
                </div>
                {useCustom && (
                    <textarea
                        value={customKws}
                        onChange={e => setCustomKws(e.target.value)}
                        placeholder={'berberine supplement India\nshilajit gold India\npostbiotic skincare India\n...'}
                        rows={5}
                        style={{ width: '100%', boxSizing: 'border-box', background: 'var(--bg-deep)', border: '1px solid var(--border-dim)', borderRadius: 6, padding: '8px 10px', color: 'var(--text-1)', fontSize: 12, fontFamily: 'var(--f-mono)', resize: 'vertical' }}
                    />
                )}
            </div>

            {/* Generate button */}
            <div style={{ marginBottom: 24 }}>
                <button onClick={generateReport} disabled={loading}
                    style={{ padding: '11px 28px', background: loading ? 'rgba(255,255,255,0.1)' : 'var(--gold)', border: 'none', borderRadius: 8, fontSize: 14, fontWeight: 700, color: '#07090D', cursor: loading ? 'default' : 'pointer' }}>
                    {loading ? `⟳ Scanning ${progress}%...` : generated ? '↻ Refresh Digest' : '📊 Generate Weekly Digest'}
                </button>
                {loading && (
                    <div style={{ marginTop: 10, height: 4, background: 'rgba(255,255,255,0.08)', borderRadius: 2 }}>
                        <div style={{ height: '100%', width: progress + '%', background: 'var(--gold)', borderRadius: 2, transition: 'width 0.4s' }} />
                    </div>
                )}
            </div>

            {/* Results */}
            {results.length > 0 && (
                <div style={{ marginBottom: 24 }}>
                    {/* Top 3 podium */}
                    {results.length >= 3 && (
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10, marginBottom: 20 }}>
                            {results.slice(0, 3).map(function (r, i) {
                                var medals = ['🥇', '🥈', '🥉']
                                return (
                                    <div key={r.keyword} className="card" style={{ padding: 16, textAlign: 'center', borderColor: i === 0 ? 'rgba(0,212,170,0.4)' : undefined }}>
                                        <div style={{ fontSize: 20, marginBottom: 6 }}>{medals[i]}</div>
                                        <div style={{ fontSize: 24, fontWeight: 800, color: scoreColor(r.momentumAccelerationScore), fontFamily: 'var(--f-mono)' }}>{r.momentumAccelerationScore}</div>
                                        <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-1)', marginTop: 6, lineHeight: 1.3 }}>{r.keyword}</div>
                                        <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 3 }}>{r.classification?.emoji} {r.classification?.label}</div>
                                        <button onClick={() => onAnalyze && onAnalyze(r.keyword)} style={{ marginTop: 10, padding: '5px 12px', fontSize: 10, fontWeight: 700, background: 'var(--gold)', border: 'none', borderRadius: 4, color: '#07090D', cursor: 'pointer', width: '100%' }}>Analyse →</button>
                                    </div>
                                )
                            })}
                        </div>
                    )}

                    {/* Full list */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                        {results.map(function (r, i) {
                            var score = r.momentumAccelerationScore || 0
                            var color = scoreColor(score)
                            return (
                                <div key={r.keyword} className="card" style={{ padding: '14px 18px', display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
                                    <div style={{ fontFamily: 'var(--f-mono)', fontSize: 16, fontWeight: 700, color: 'var(--text-3)', width: 24, textAlign: 'center' }}>{i + 1}</div>
                                    <div style={{ width: 48, height: 48, borderRadius: '50%', flexShrink: 0, border: '2px solid ' + color, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-float)' }}>
                                        <div style={{ fontSize: 15, fontWeight: 700, color, fontFamily: 'var(--f-mono)', lineHeight: 1 }}>{score}</div>
                                        <div style={{ fontSize: 6, color: 'var(--text-3)', fontFamily: 'var(--f-mono)' }}>MAS</div>
                                    </div>
                                    <div style={{ flex: 1, minWidth: 140 }}>
                                        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-1)', marginBottom: 4 }}>{r.keyword}</div>
                                        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                                            <span className={'badge ' + classBadge(r.classification?.label)} style={{ fontSize: 9, padding: '2px 7px' }}>{r.classification?.emoji} {r.classification?.label}</span>
                                            <span style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--f-mono)' }}>₹{r.marketSizePotential?.tam || 0}Cr TAM</span>
                                            <span style={{ fontSize: 10, color: r.signals?.trendDirection === 'rising' ? 'var(--teal)' : 'var(--text-3)', fontFamily: 'var(--f-mono)' }}>{r.signals?.trendDirection === 'rising' ? '↑' : r.signals?.trendDirection === 'declining' ? '↓' : '→'} {r.signals?.trendDirection || 'stable'}</span>
                                        </div>
                                    </div>
                                    {onAnalyze && (
                                        <button onClick={() => onAnalyze(r.keyword)} style={{ padding: '6px 14px', background: 'rgba(45,212,191,0.06)', border: '1px solid rgba(45,212,191,0.2)', borderRadius: 6, cursor: 'pointer', fontSize: 11, color: 'var(--teal)', fontFamily: 'var(--f-mono)' }}>Analyse →</button>
                                    )}
                                </div>
                            )
                        })}
                    </div>
                </div>
            )}

            {/* Email subscribe + send digest */}
            <div style={{ padding: 24, background: 'rgba(45,212,191,0.04)', border: '1px solid rgba(45,212,191,0.2)', borderRadius: 'var(--radius)' }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--teal)', marginBottom: 6 }}>📬 Email This Digest</div>
                <div style={{ fontSize: 12, color: 'var(--text-2)', marginBottom: 16, lineHeight: 1.6 }}>
                    Enter your email to receive this digest — or to save it for weekly delivery every Monday.
                </div>
                {emailSent ? (
                    <div style={{ fontSize: 13, color: 'var(--teal)', fontWeight: 600 }}>✅ Digest sent to {email}!</div>
                ) : (
                    <>
                        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 10 }}>
                            <input type="email" value={email} onChange={e => setEmail(e.target.value)}
                                onKeyDown={e => { if (e.key === 'Enter') handleSubscribe() }}
                                placeholder="your@email.com"
                                style={{ flex: 1, minWidth: 200, fontSize: 13 }} />
                            <button className="btn btn-primary" onClick={handleSubscribe} disabled={!email.includes('@')} style={{ height: 42 }}>
                                {subscribed ? '✅ Saved' : 'Subscribe →'}
                            </button>
                            {generated && results.length > 0 && (
                                <button className="btn btn-ghost" onClick={sendDigestEmail} disabled={sending || !email.includes('@')} style={{ height: 42, fontSize: 12 }}>
                                    {sending ? '⟳ Sending...' : '📧 Send Now'}
                                </button>
                            )}
                        </div>
                        {emailError && <div style={{ fontSize: 11, color: 'var(--red)' }}>⚠ {emailError}</div>}
                    </>
                )}
            </div>
        </div>
    )
}